name: "Hello Actions"
description: "greating someone"
author: " octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to Greet"
    required: true
    default: "World"
    
runs:
  using: "docker"
  image: "Dockerfile"
  
branding:
  icon: "mic"
  color: "purple"
  
  
  
  
